// <auto-generated />
using Consoli_Ricette.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Consoli_Ricette.Migrations
{
    [DbContext(typeof(Consoli_RicetteContext))]
    partial class Consoli_RicetteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Consoli_Ricette.Models.Recipe", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("authorId");

                    b.Property<string>("authorName");

                    b.Property<string>("description");

                    b.Property<int>("difficulty");

                    b.Property<string>("ingredients");

                    b.Property<string>("procedures");

                    b.Property<int>("time");

                    b.HasKey("id");

                    b.ToTable("Recipe");
                });
#pragma warning restore 612, 618
        }
    }
}
